### ISSUE TITLE
Iban string length

### ISSUE THREAD

**Issue by vlefr** [readefries/IBAN-Helper#1]
Hello,

I have a crash if the iban string checked length is < 4.

**Comment by readefries** [comment]
Hey qliam,

Sorry for not responding earlier. I will take a look at it, as it shouldn't crash. Although an IBAN can never have a length < 4. Can you elaborate when this happens?

BR Hindrik

**Comment by readefries** [comment]
OK, I created a new release which contains a test to see if the BBAN part of the IBAN is empty.
If this doesn't work for you, please reopen this issue and let me know more about the issue you're facing.

**Comment by vlefr** [comment]
Thanks a lot readefries ! I'm trying that
