### ISSUE TITLE
Crash wrong count IBAN Numbers

### ISSUE THREAD

**Issue by felixAppsideMe** [readefries/IBAN-Helper#10]
If I type in a IBAN and delete the last character and perform isValidIBAN() the IBAN-Helper crashed. I think you miss to check the length of the String, with the length you have in structure.

**Comment by sjoerdvisscher** [comment]
I get the crash too, on the line:

    let innerPart = String(bban[bban.index(bban.startIndex, offsetBy: bbanOfset)..<bban.index(bban.startIndex, offsetBy: bbanOfset + formatLength)])

**Comment by readefries** [comment]
Hey, thanks for letting me know! I will take a look at it.

**Comment by readefries** [comment]
Ok, it should be fixed in version `3.0.1`. Can you verify this?
