### ISSUE TITLE
_Pods.xcodeproj file is pointing to an inexistent file

### ISSUE THREAD

**Issue by tjanela** [readefries/IBAN-Helper#11]
This file 
https://github.com/readefries/IBAN-Helper/blob/master/_Pods.xcodeproj

is pointing to an inexisting file.
This is causing problems at our CI server.
We have remediated the issue by removing the file.

**Comment by readefries** [comment]
Hey Tiago,

Thanks for getting in touch. 
I’ll take a look at it, somewhere this week. 

Cheers!

**Comment by readefries** [comment]
Hey Tiago,

Sorry it took a while, I just updated to 3.0.2 with the file removes the file.

Cheers.

**Comment by tjanela** [comment]
No worries @readefries.
Thanks for the update!
