### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jcpp7** [readefries/IBAN-Helper#12]
Good morning and thank you for your work. I am using your library and I am received an error when I validate a short iban (Ex: ES1111...). How can I solve it? Thanks
![Captura de pantalla 2019-03-22 a las 11 33 43](https://user-images.githubusercontent.com/39334540/54817115-62542d80-4c96-11e9-8f7c-14f2a60e37db.png)

**Comment by jcpp7** [comment]
I have downloaded the 3.0.2 version and I am getting a similar error with the new code.
![Captura de pantalla 2019-03-22 a las 11 52 07](https://user-images.githubusercontent.com/39334540/54818196-ffb06100-4c98-11e9-85e5-d85c2559a2e4.png)

**Comment by jcpp7** [comment]
I have cleaned the project, re built the framework, closed Xcode and now it is working with the 3.0.2 version. I close the issue. Thanks!

**Comment by readefries** [comment]
Good to hear you fixed it by rebuilding :)
