### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by H2wk** [readefries/IBAN-Helper#2]
Any plans to update the Code for the official release of swift 3? Get pod file errors when importing into swift 3 project via cocoapods.

`ISO7064.swift: Value of optional type 'Int?' not unwrapped; did you mean to use '!' or '?'?`
`RFIBANHelper.swift: Type 'String.CompareOptions' (aka 'NSString.CompareOptions') has no member 'regularExpressionSearch'`

**Comment by readefries** [comment]
I'll publish an update today or tomorrow.

**Comment by readefries** [comment]
Ok, I pushed 2.0.0 with Swift 3 support to Cocoapods.
