### ISSUE TITLE
Not working for empty string

### ISSUE THREAD

**Issue by marcelUF** [readefries/IBAN-Helper#4]
Should the library not be supported to receive:
let IBAN = ""
or
let IBAN = "ES"

And return false.

Now is crashing the App if this is tested.

**Comment by readefries** [comment]
Hey Marcel,

thanks for you remark. I will look at it tomorrow.

BR Hindrik

**Comment by readefries** [comment]
Hey Marcel,

Can you verify that the PR I created (https://github.com/readefries/IBAN-Helper/pull/5) solves the problem?

You can try it out, by adding it temporarily to your Podfile like this:
`pod 'RFIBAN-Helper', :git => 'https://github.com/readefries/IBAN-Helper.git', :commit => '4836f43664490ddf3d7f3b82e839d72fb07a6ae3'`.

If this solves your problem, then I'll release an update to cocoapods.

BR Hindrik

**Comment by readefries** [comment]
Released version 2.0.1 which should fix this.
Please let me know if you run into any more issues.

**Comment by YWinters** [comment]
Still happening..
