### ISSUE TITLE
Swift4 Support?

### ISSUE THREAD

**Issue by rocketes** [readefries/IBAN-Helper#9]
Hello,

is it possible to upgrade your repo to swift4?

Thanks in advance

**Comment by readefries** [comment]
Good question! I'll do that.

**Comment by rocketes** [comment]
Thank you so much!

**Comment by readefries** [comment]
Ok, I released a new version for Swift 4.

Just update your pod, to use 3.0, and you're all set!

`pod 'RFIBAN-Helper', '~> 3.0'`
